// Package aistudio_proxy manages a self-hosted aistudio-api Python subprocess per
// Gemini account that opts into the "AIStudio reverse proxy" (Bearer) mode.
//
// One aistudio-api process == one headless browser == one Google account session.
// LB allocates a local port, injects a random bearer token (AISTUDIO_API_KEY),
// persists {base_url, api_key, auth_header:bearer} into the account credentials,
// and the existing Gemini forwarding stack (see UsesBearerAuth / setGeminiAPIKeyAuth)
// routes requests through the local subprocess transparently.
package aistudio_proxy

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"
)

// AccountCredentialUpdater persists the runtime connection info (base_url / api_key)
// generated by the manager back into the account so the forwarding stack and any
// surviving-on-restart EnsureRunning call see the same values.
type AccountCredentialUpdater interface {
	UpdateCredentials(ctx context.Context, accountID int64, credentials map[string]any) error
}

// AccountCredentialReader loads the current credentials map for an account.
// Used to preserve existing keys when persisting runtime info.
type AccountCredentialReader interface {
	GetCredentials(ctx context.Context, accountID int64) (map[string]any, error)
}

// Config configures the manager. DataDir is the LB data root (e.g. "data");
// the per-account workdir is <DataDir>/aistudio-proxy/<accountID>.
// RuntimeDir is the directory containing the aistudio-api checkout (with main.py);
// it may be empty in M1 (assumed pre-installed at a known location).
type Config struct {
	// DataDir is the LB data root used for per-account workdirs.
	DataDir string
	// RuntimeDir is the directory that contains the aistudio-api main.py.
	// If empty, DefaultRuntimeDir (DataDir/aistudio-proxy/runtime) is used.
	RuntimeDir string
	// PythonBin is the python interpreter used to launch the server (default "python3").
	PythonBin string
	// PortStart / PortEnd define the loopback port range assigned to subprocesses.
	PortStart int
	PortEnd   int
	// HealthTimeout is how long EnsureRunning waits for /health to turn ok.
	HealthTimeout time.Duration
	// HTTPClient used for health probing (injected for testability).
	HTTPClient *http.Client
}

// Instance describes a running aistudio-api subprocess for one account.
type Instance struct {
	AccountID   int64
	Port        int
	BaseURL     string // http://127.0.0.1:<port>
	BearerToken string
	PID         int
	WorkDir     string
	Status      Status
	cmd         *exec.Cmd
}

// Status is the lifecycle state of a managed instance.
type Status string

const (
	StatusStarting Status = "starting"
	StatusRunning  Status = "running"
	StatusFailed   Status = "failed"
	StatusStopped  Status = "stopped"
)

const (
	defaultPortStart     = 19000
	defaultPortEnd       = 19499
	defaultHealthTimeout = 90 * time.Second
	healthProbeInterval  = 500 * time.Millisecond
	// runtimeSubdir is the aistudio-api checkout location under DataDir.
	runtimeSubdir = "aistudio-proxy" // <DataDir>/aistudio-proxy
)

// Manager owns the lifecycle of per-account aistudio-api subprocesses.
// It is safe for concurrent use.
type Manager struct {
	cfg       Config
	creds     AccountCredentialUpdater
	reader    AccountCredentialReader
	installer *Installer

	mu        sync.Mutex
	instances map[int64]*Instance
	allocated map[int]struct{} // ports currently in use by managed processes

	httpClient *http.Client
}

// NewManager constructs a manager. creds may be nil (persistence disabled),
// reader may be nil (will not preserve existing credentials).
func NewManager(cfg Config, creds AccountCredentialUpdater, reader AccountCredentialReader) *Manager {
	if cfg.PortStart <= 0 {
		cfg.PortStart = defaultPortStart
	}
	if cfg.PortEnd < cfg.PortStart {
		cfg.PortEnd = defaultPortEnd
	}
	if cfg.HealthTimeout <= 0 {
		cfg.HealthTimeout = defaultHealthTimeout
	}
	if strings.TrimSpace(cfg.PythonBin) == "" {
		cfg.PythonBin = "python3"
	}
	cfg.RuntimeDir = strings.TrimSpace(cfg.RuntimeDir)
	if cfg.RuntimeDir == "" {
		cfg.RuntimeDir = filepath.Join(strings.TrimSpace(cfg.DataDir), runtimeSubdir)
	}
	hc := cfg.HTTPClient
	if hc == nil {
		hc = &http.Client{Timeout: 3 * time.Second}
	}
	return &Manager{
		cfg:        cfg,
		creds:      creds,
		reader:     reader,
		installer:  NewInstaller(cfg),
		instances:  make(map[int64]*Instance),
		allocated:  make(map[int]struct{}),
		httpClient: hc,
	}
}

// Installer returns the runtime installer bound to this manager.
func (m *Manager) Installer() *Installer {
	if m == nil {
		return nil
	}
	return m.installer
}

// EnsureRunning guarantees an aistudio-api subprocess for accountID is up and
// healthy, returning its connection info. It is idempotent: a healthy running
// instance is returned without re-launching.
//
// The account's credentials map is updated with base_url/api_key/auth_header so
// the Gemini forwarding stack routes to this subprocess. The caller is expected
// to have already validated that the account is a Gemini APIKey account with
// auth_header=bearer (UsesBearerAuth).
func (m *Manager) EnsureRunning(ctx context.Context, accountID int64) (*Instance, error) {
	if m == nil {
		return nil, errors.New("aistudio_proxy manager is not configured")
	}
	if accountID <= 0 {
		return nil, errors.New("invalid account id")
	}

	m.mu.Lock()
	if inst := m.instances[accountID]; inst != nil && inst.Status == StatusRunning && processAlive(inst.cmd) {
		m.mu.Unlock()
		return inst, nil
	}
	m.mu.Unlock()

	return m.launch(ctx, accountID)
}

func (m *Manager) launch(ctx context.Context, accountID int64) (*Instance, error) {
	// Gate on runtime readiness: avoid spawning a doomed subprocess if the
	// aistudio-api checkout / python is missing. Best-effort; ignore probe errors.
	if m.installer != nil {
		if status, err := m.installer.Detect(ctx); err == nil && status != nil {
			if !status.AistudioInstalled || !status.PythonOK {
				return nil, fmt.Errorf("%w: python_ok=%v aistudio_installed=%v", ErrInstallerNotReady, status.PythonOK, status.AistudioInstalled)
			}
		}
	}

	port, err := m.allocatePortLocked()
	if err != nil {
		return nil, err
	}

	workDir := filepath.Join(m.cfg.RuntimeDir, "accounts-workdir", strconv.FormatInt(accountID, 10))
	if err := os.MkdirAll(filepath.Join(workDir, "accounts"), 0o755); err != nil {
		m.releasePortLocked(port)
		return nil, fmt.Errorf("create workdir: %w", err)
	}

	bearer := generateToken()
	mainPy := filepath.Join(m.cfg.RuntimeDir, "main.py")
	if info, statErr := os.Stat(mainPy); statErr != nil || info.IsDir() {
		m.releasePortLocked(port)
		return nil, fmt.Errorf("aistudio-api main.py not found at %s (install the runtime first)", mainPy)
	}

	cmd := exec.CommandContext(context.Background(), m.cfg.PythonBin, mainPy, "server", "--port", strconv.Itoa(port))
	cmd.Dir = m.cfg.RuntimeDir
	cmd.Env = append(os.Environ(),
		"PYTHONUNBUFFERED=1",
		"AISTUDIO_PORT="+strconv.Itoa(port),
		"AISTUDIO_API_KEY="+bearer,
		"AISTUDIO_BROWSER=chromium",
		"AISTUDIO_BROWSER_HEADLESS=1",
		"AISTUDIO_CHROMIUM_SANDBOX=0",
		"AISTUDIO_ACCOUNTS_DIR="+filepath.Join(workDir, "accounts"),
		"AISTUDIO_TMP_DIR="+filepath.Join(workDir, "tmp"),
	)
	// Stream subprocess logs to LB's stderr for diagnosability.
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	inst := &Instance{
		AccountID:   accountID,
		Port:        port,
		BaseURL:     fmt.Sprintf("http://127.0.0.1:%d", port),
		BearerToken: bearer,
		WorkDir:     workDir,
		Status:      StatusStarting,
	}

	if err := cmd.Start(); err != nil {
		m.releasePortLocked(port)
		return nil, fmt.Errorf("start aistudio-api subprocess: %w", err)
	}
	inst.PID = cmd.Process.Pid
	inst.cmd = cmd

	m.mu.Lock()
	m.instances[accountID] = inst
	m.mu.Unlock()

	// Reap the process asynchronously; flip status on exit.
	go func() {
		waitErr := cmd.Wait()
		m.mu.Lock()
		cur := m.instances[accountID]
		if cur == inst {
			if waitErr != nil && cur.Status != StatusStopped {
				cur.Status = StatusFailed
			} else if cur.Status != StatusStopped {
				cur.Status = StatusStopped
			}
			m.releasePortLocked(cur.Port)
		}
		m.mu.Unlock()
	}()

	// Persist connection info so the forwarding stack (and post-restart EnsureRunning) see it.
	m.persistCredentials(accountID, inst)

	// Wait for /health to report ok.
	if err := m.waitHealthy(ctx, inst); err != nil {
		// Don't leave a half-alive process; best-effort stop.
		_ = m.Stop(context.Background(), accountID)
		return nil, fmt.Errorf("aistudio-api did not become healthy: %w", err)
	}

	m.mu.Lock()
	inst.Status = StatusRunning
	m.mu.Unlock()
	return inst, nil
}

// waitHealthy polls the subprocess /health endpoint until it returns ok or the
// timeout elapses. Note: /health only proves the HTTP layer is up; the browser
// warms lazily on first real request (see plan, M1 risks).
func (m *Manager) waitHealthy(ctx context.Context, inst *Instance) error {
	deadline := time.Now().Add(m.cfg.HealthTimeout)
	url := inst.BaseURL + "/health"
	for {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		if time.Now().After(deadline) {
			return errors.New("health probe timeout")
		}
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
		if err == nil {
			resp, doErr := m.httpClient.Do(req)
			if doErr == nil {
				body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<16))
				_ = resp.Body.Close()
				if resp.StatusCode == http.StatusOK && strings.Contains(strings.ToLower(string(body)), `"ok"`) {
					return nil
				}
			}
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(healthProbeInterval):
		}
	}
}

// persistCredentials writes the runtime connection info into the account's
// credentials map. Existing keys (e.g. model_mapping) are preserved.
func (m *Manager) persistCredentials(accountID int64, inst *Instance) {
	if m.creds == nil {
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	creds := map[string]any{}
	if m.reader != nil {
		if existing, err := m.reader.GetCredentials(ctx, accountID); err == nil {
			creds = existing
			if creds == nil {
				creds = map[string]any{}
			}
		}
	}
	creds["base_url"] = inst.BaseURL
	creds["api_key"] = inst.BearerToken
	creds["auth_header"] = "bearer"

	if err := m.creds.UpdateCredentials(ctx, accountID, creds); err != nil {
		// Non-fatal: the in-memory instance is still usable for this process lifetime.
		fmt.Fprintf(os.Stderr, "aistudio_proxy: failed to persist credentials for account %d: %v\n", accountID, err)
	}
}

// Stop terminates the subprocess for a single account (idempotent).
func (m *Manager) Stop(ctx context.Context, accountID int64) error {
	if m == nil {
		return nil
	}
	m.mu.Lock()
	inst := m.instances[accountID]
	if inst == nil {
		m.mu.Unlock()
		return nil
	}
	inst.Status = StatusStopped
	cmd := inst.cmd
	m.mu.Unlock()

	if cmd != nil && cmd.Process != nil {
		_ = cmd.Process.Kill()
	}
	return nil
}

// StopAll terminates every managed subprocess. Registered as a cleanup step.
// Safe to call on a nil receiver (no-op), since cleanup always runs.
func (m *Manager) StopAll() {
	if m == nil {
		return
	}
	m.mu.Lock()
	ids := make([]int64, 0, len(m.instances))
	for id := range m.instances {
		ids = append(ids, id)
	}
	m.mu.Unlock()
	for _, id := range ids {
		_ = m.Stop(context.Background(), id)
	}
}

// StatusOf returns the current status of an account's instance (StatusStopped
// if none). Safe for nil receiver / unknown accounts.
func (m *Manager) StatusOf(accountID int64) Status {
	if m == nil {
		return StatusStopped
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if inst := m.instances[accountID]; inst != nil {
		return inst.Status
	}
	return StatusStopped
}

// allocatePortLocked finds a free loopback port not already tracked by the
// manager. Caller must hold responsibility; the bookkeeping is mutex-guarded.
func (m *Manager) allocatePortLocked() (int, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	for port := m.cfg.PortStart; port <= m.cfg.PortEnd; port++ {
		if _, taken := m.allocated[port]; taken {
			continue
		}
		if !portIsFree(port) {
			continue
		}
		m.allocated[port] = struct{}{}
		return port, nil
	}
	return 0, errors.New("no free port in aistudio-proxy range")
}

func (m *Manager) releasePortLocked(port int) {
	if port <= 0 {
		return
	}
	m.mu.Lock()
	delete(m.allocated, port)
	m.mu.Unlock()
}

// --- helpers ---

func portIsFree(port int) bool {
	ln, err := net.Listen("tcp", net.JoinHostPort("127.0.0.1", strconv.Itoa(port)))
	if err != nil {
		return false
	}
	_ = ln.Close()
	return true
}

func processAlive(cmd *exec.Cmd) bool {
	if cmd == nil || cmd.Process == nil {
		return false
	}
	// signal 0 probes process existence without delivering a real signal.
	return cmd.Process.Signal(syscall.Signal(0)) == nil
}

func generateToken() string {
	b := make([]byte, 24)
	if _, err := rand.Read(b); err != nil {
		// Extremely unlikely; fall back to time-based hex.
		return strconv.FormatInt(time.Now().UnixNano(), 16)
	}
	return "lbaip_" + hex.EncodeToString(b)
}

// Snapshot returns a JSON-safe view of all managed instances (for debugging/admin).
func (m *Manager) Snapshot() []map[string]any {
	if m == nil {
		return nil
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	out := make([]map[string]any, 0, len(m.instances))
	for _, inst := range m.instances {
		out = append(out, map[string]any{
			"account_id": inst.AccountID,
			"port":       inst.Port,
			"base_url":   inst.BaseURL,
			"pid":        inst.PID,
			"status":     string(inst.Status),
		})
	}
	return out
}

// MarshalJSON for Instance (excludes the unexported cmd field).
func (in *Instance) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]any{
		"account_id": in.AccountID,
		"port":       in.Port,
		"base_url":   in.BaseURL,
		"pid":        in.PID,
		"status":     string(in.Status),
	})
}
